# Generated by Django 4.0.7 on 2022-08-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mt613',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('unit', models.IntegerField()),
                ('session', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mt722',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('unit', models.IntegerField()),
                ('session', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mt723',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('unit', models.IntegerField()),
                ('session', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
